from django.urls import path
from . import views


urlpatterns = [
    path('', views.index, name='index'),
    path('about', views.about, name='about'),
    path('leader', views.leader, name='leader'),
    path('market', views.market, name='market'),
    path('partnerships-program', views.partnerships_program, name='partnerships-program'),
    path('become-leader', views.become_leader, name='become-leader'),
    path('support', views.support, name='support'),
    path('calender', views.calender, name='calender'),
    path('user-guide', views.user_guide, name='user-guide'),
    path('help-center', views.help_center, name='help-center'),
    path('leader-guide', views.leader_guide, name='leader-guide'),
    path('privacy-policy', views.privacy_policy, name='privacy-policy'),
    path('cookies-policy', views.cookies_policy, name='cookies-policy'),
    path('risk-disclaimer', views.risk_disclaimer, name='risk-disclaimer'),
    path('autoprotect', views.autoprotect, name='autoprotect'),
    path('affiliate-guide', views.affiliate_guide, name='affiliate-guide'),
    path('become-leader', views.become_leader, name='become-leader'),
    path('become-affiliate', views.become_affiliate, name='become-affiliate'),
    path('login', views.login, name='login'),
    path('register', views.register, name='register'),
    path('forgotten-password', views.password_reset_request, name='password-reset-request'),
    path('reset-password/<str:uidb64>/<str:token>/', views.password_reset, name='password-reset'),
    path('complete-profile', views.complete_profile, name='complete-profile'),
    path('dashboard/', views.dashboard, name='dashboard'),
    path('dashboard/buy-plan', views.buy_plan, name='buy-plan'),
    path('dashboard/account-history', views.account_history, name='account-history'),
    path('dashboard/portfolio', views.portfolio, name='portfolio'),
    path('dashboard/trading-history', views.trading_history, name='trading-history'),
    path('dashboard/trading', views.trading, name='trading'),
    path('dashboard/copy-trading', views.copy_trading, name='copy-trading'),
    path('dashboard/copy-trade-experts', views.copy_trade_experts, name='copy-trade-experts'),
    path('dashboard/bot-trading', views.bot_trading, name='bot-trading'),
    path('dashboard/bot-trading/dashboard', views.bot_trading_dahboard, name='bot-trading-dashboard'),
    path('dashboard/premium-signals', views.signal, name='signal'),
    path('dashboard/withdrawals', views.withdrawals, name='withdrawals'),
    path('dashboard/transfer-funds', views.transfer_funds, name='transfer-funds'),
    path('dashboard/loans', views.loans, name='loans'),
    path('dashboard/loan-history', views.loan_history, name='loan-history'),
    path('dashboard/support', views.support, name='support'),
    # path('dashboard/payments/', views.payments, name='payments'),
    path('dashboard/account-settings', views.account_settings, name='account-settings'),
    path('dashboard/refer-user/', views.refer_user, name='refer-user'),
    path('dashboard/verify-account/', views.verify_account, name='verify-account'),
    path('dashboard/kyc-form', views.kyc_form, name='kyc-form'),
    path('dashboard/connect-wallet/', views.connect_wallet, name='connect-wallet'),
    path('dashboard/notifications/', views.notifications, name='notifications'),
    # path('dashboard/deposit-step1', views.process_deposit_step1, name='deposit-step1'),
    path('dashboard/deposits', views.deposits, name='deposits'),
    path('dashboard/payments/', views.payments, name='payments'),
    path('dashboard/deposit-success/', views.deposit_success, name='deposit-success'),
    path('dashboard/join-investment/', views.join_investment, name='join-investment'),
    path('dashboard/investment-history/', views.investment_history, name='investment-history'),
    path('dashboard/trading-view/<int:pairId>/', views.trading_view, name='trading-view'),
    path('dashboard/trading-view2/', views.trading_view2, name='trading-view2'),
    path('dashboard/transactions/', views.transactions, name='transactions'),
    path('dashboard/transactions/<int:transaction_id>/', views.transaction_details, name='transaction-details'),
    path('dashboard/copy-trading/experts/', views.copy_trading_experts, name='copy-trading-experts'),
    
]