# Generated by Django 5.2.8 on 2025-11-24 00:50

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_profile_profile_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='referral_code',
        ),
        migrations.RemoveField(
            model_name='user',
            name='referred_by',
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_available_balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Balance available for withdrawal or new investments', max_digits=20)),
                ('total_deposits', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total deposits made', max_digits=20)),
                ('total_withdrawals', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total withdrawals made', max_digits=20)),
                ('pending_deposits', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Amount in pending deposits', max_digits=20)),
                ('pending_withdrawals', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Amount in pending withdrawals', max_digits=20)),
                ('pending_investments', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Amount in pending investments', max_digits=20)),
                ('referral_balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Balance earned from referrals', max_digits=20)),
                ('total_referral_earnings', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total earnings from referrals', max_digits=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('suspended', 'Suspended'), ('disabled', 'Disabled'), ('penalized', 'Penalized'), ('blocked', 'Blocked'), ('under_review', 'Under Review')], default='active', max_length=20)),
                ('withdrawal_limit', models.DecimalField(decimal_places=2, default=Decimal('10000.00'), help_text='Maximum withdrawal amount per transaction', max_digits=20)),
                ('daily_withdrawal_limit', models.DecimalField(decimal_places=2, default=Decimal('50000.00'), help_text='Maximum withdrawal amount per day', max_digits=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('last_investment', models.DateTimeField(blank=True, null=True)),
                ('last_withdrawal', models.DateTimeField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='main_account', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Main User Account',
                'verbose_name_plural': 'Main User Accounts',
                'db_table': 'main_user_account',
            },
        ),
        migrations.CreateModel(
            name='Referral',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('referral_code', models.CharField(help_text='Unique referral code for this user', max_length=10, unique=True)),
                ('total_referrals', models.PositiveIntegerField(default=0, help_text='Total number of successful referrals')),
                ('current_tier', models.CharField(choices=[('starter', 'Starter (0-9 referrals) - 5%'), ('bronze', 'Bronze (10-24 referrals) - 7%'), ('silver', 'Silver (25-49 referrals) - 10%'), ('gold', 'Gold (50-99 referrals) - 12%'), ('elite', 'Elite (100+ referrals) - 15%')], default='starter', help_text='Current commission tier', max_length=20)),
                ('total_commission_earned', models.DecimalField(decimal_places=2, default=0.0, help_text='Total commission earned from referrals', max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('referred_by', models.ForeignKey(blank=True, help_text='User who referred this user', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referred_users', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='referral', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Referral',
                'verbose_name_plural': 'Referrals',
                'ordering': ['-total_referrals', '-created_at'],
                'indexes': [models.Index(fields=['referral_code'], name='users_refer_referra_3adb75_idx'), models.Index(fields=['current_tier'], name='users_refer_current_5ebcdd_idx')],
            },
        ),
        migrations.CreateModel(
            name='ReferralEarning',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('transaction_type', models.CharField(help_text='Type of transaction that generated commission', max_length=50)),
                ('transaction_amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('commission_rate', models.DecimalField(decimal_places=2, help_text='Commission rate applied (percentage)', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('commission_earned', models.DecimalField(decimal_places=2, help_text='Commission amount earned', max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('tier_at_earning', models.CharField(choices=[('starter', 'Starter (0-9 referrals) - 5%'), ('bronze', 'Bronze (10-24 referrals) - 7%'), ('silver', 'Silver (25-49 referrals) - 10%'), ('gold', 'Gold (50-99 referrals) - 12%'), ('elite', 'Elite (100+ referrals) - 15%')], help_text="Referrer's tier when commission was earned", max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('referred_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generated_earnings', to=settings.AUTH_USER_MODEL)),
                ('referrer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referral_earnings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Referral Earning',
                'verbose_name_plural': 'Referral Earnings',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['referrer', '-created_at'], name='users_refer_referre_ee05ab_idx'), models.Index(fields=['referred_user', '-created_at'], name='users_refer_referre_cd2ac3_idx')],
            },
        ),
    ]
