# Generated by Django 5.2.8 on 2025-11-25 13:18

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_remove_user_referral_code_remove_user_referred_by_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='daily_withdrawal_limit',
        ),
        migrations.RemoveField(
            model_name='account',
            name='referral_balance',
        ),
        migrations.RemoveField(
            model_name='account',
            name='withdrawal_limit',
        ),
        migrations.AddField(
            model_name='account',
            name='total_commission_earned',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total commission earned', max_digits=20),
        ),
        migrations.AddField(
            model_name='account',
            name='total_investments',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total investments made', max_digits=20),
        ),
        migrations.AlterField(
            model_name='account',
            name='main_available_balance',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Main Balance available for withdrawal, trading, and new investments', max_digits=20),
        ),
        migrations.AlterField(
            model_name='account',
            name='total_referral_earnings',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total referral earnings', max_digits=20),
        ),
    ]
