# Generated by Django 5.2.8 on 2025-11-25 14:09

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_remove_account_daily_withdrawal_limit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='total_deposit_balance',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total deposit balance', max_digits=20),
        ),
    ]
