# Generated by Django 5.2.8 on 2025-11-26 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_account_total_deposit_balance'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Account',
        ),
    ]
