# Generated by Django 5.2.8 on 2025-11-26 11:21

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_delete_account'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('available_balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Balance available for withdrawal or new investments', max_digits=20)),
                ('invested_balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total amount currently in active investments', max_digits=20)),
                ('pending_balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Balance pending confirmation or processing', max_digits=20)),
                ('total_invested', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total amount invested across all time', max_digits=20)),
                ('active_investments', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Current active investment amount', max_digits=20)),
                ('total_earned', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total earnings from investments', max_digits=20)),
                ('deposit_balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total deposit balance', max_digits=20)),
                ('total_deposits', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total deposits made', max_digits=20)),
                ('total_withdrawals', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total withdrawals made', max_digits=20)),
                ('pending_withdrawals', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Amount in pending withdrawals', max_digits=20)),
                ('pending_investments', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Amount in pending investments', max_digits=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('suspended', 'Suspended'), ('disabled', 'Disabled'), ('penalized', 'Penalized'), ('blocked', 'Blocked'), ('under_review', 'Under Review')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('last_investment', models.DateTimeField(blank=True, null=True)),
                ('last_withdrawal', models.DateTimeField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='account', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Account',
                'verbose_name_plural': 'User Accounts',
                'db_table': 'user_account',
            },
        ),
    ]
