# Generated by Django 5.2.8 on 2025-11-26 17:21

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='trading_balance',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Balance available for trading', max_digits=20),
        ),
    ]
