# Generated by Django 5.2.8 on 2025-11-26 17:23

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_account_trading_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='pending_deposit',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Deposit pending confirmation or processing', max_digits=20),
        ),
        migrations.AddField(
            model_name='account',
            name='pending_withdrawal',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Withdrawal pending confirmation or processing', max_digits=20),
        ),
    ]
