# Generated by Django 5.2.8 on 2025-11-26 17:47

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_account_pending_deposit_account_pending_withdrawal'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='investment_balance',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Balance available for investment', max_digits=20),
        ),
    ]
