# Generated by Django 5.2.8 on 2025-11-26 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_account_investment_balance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='pending_investments',
        ),
    ]
