# Generated by Django 5.2.8 on 2025-11-27 23:52

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_remove_account_pending_investments'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='locked_trading_balance',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Trading balance locked in open orders', max_digits=20),
        ),
    ]
