# Generated by Django 5.2.8 on 2025-12-05 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_profile_display_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['email']},
        ),
    ]
