# Generated by Django 5.2.8 on 2025-11-09 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BotTrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signal_data', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='TradingBot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('strategy', models.CharField(choices=[('moving_average', 'Moving Average Crossover'), ('rsi', 'RSI Strategy'), ('macd', 'MACD Strategy'), ('bollinger', 'Bollinger Bands'), ('arbitrage', 'Arbitrage'), ('ml_model', 'Machine Learning Model'), ('custom', 'Custom Strategy')], max_length=20)),
                ('is_active', models.BooleanField(default=False)),
                ('is_paper_trading', models.BooleanField(default=True)),
                ('max_position_size', models.DecimalField(decimal_places=8, max_digits=20)),
                ('stop_loss_percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('take_profit_percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('max_daily_loss', models.DecimalField(decimal_places=2, max_digits=20)),
                ('parameters', models.JSONField(default=dict)),
                ('total_trades', models.IntegerField(default=0)),
                ('winning_trades', models.IntegerField(default=0)),
                ('total_profit', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_run_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
