# Generated by Django 5.2.8 on 2025-11-09 23:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bots', '0001_initial'),
        ('trading', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bottrade',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trading.order'),
        ),
        migrations.AddField(
            model_name='tradingbot',
            name='trading_pairs',
            field=models.ManyToManyField(to='trading.tradingpair'),
        ),
    ]
