# Generated by Django 5.2.8 on 2025-11-09 23:19

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AssetCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('trading_hours_start', models.TimeField(blank=True, null=True)),
                ('trading_hours_end', models.TimeField(blank=True, null=True)),
                ('trading_days', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Asset Categories',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_type', models.CharField(choices=[('market', 'Market'), ('limit', 'Limit'), ('stop_loss', 'Stop Loss'), ('take_profit', 'Take Profit')], max_length=20)),
                ('side', models.CharField(choices=[('buy', 'Buy'), ('sell', 'Sell')], max_length=4)),
                ('quantity', models.DecimalField(decimal_places=8, max_digits=20)),
                ('price', models.DecimalField(decimal_places=8, max_digits=20, null=True)),
                ('stop_price', models.DecimalField(decimal_places=8, max_digits=20, null=True)),
                ('filled_quantity', models.DecimalField(decimal_places=8, default=Decimal('0'), max_digits=20)),
                ('average_price', models.DecimalField(decimal_places=8, max_digits=20, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('open', 'Open'), ('partially_filled', 'Partially Filled'), ('filled', 'Filled'), ('cancelled', 'Cancelled'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('fee', models.DecimalField(decimal_places=8, default=Decimal('0'), max_digits=20)),
                ('source', models.CharField(choices=[('manual', 'Manual'), ('bot', 'AI Bot'), ('copy_trade', 'Copy Trade'), ('signal', 'Signal')], default='manual', max_length=20)),
                ('source_id', models.IntegerField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('executed_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('side', models.CharField(choices=[('long', 'Long'), ('short', 'Short')], max_length=50)),
                ('quantity', models.DecimalField(decimal_places=8, max_digits=20)),
                ('entry_price', models.DecimalField(decimal_places=8, max_digits=20)),
                ('current_price', models.DecimalField(decimal_places=8, max_digits=20)),
                ('unrealized_pnl', models.DecimalField(decimal_places=8, max_digits=20)),
                ('leverage', models.DecimalField(decimal_places=2, default=Decimal('1'), max_digits=5)),
                ('stop_loss', models.DecimalField(decimal_places=8, max_digits=20, null=True)),
                ('take_profit', models.DecimalField(decimal_places=8, max_digits=20, null=True)),
                ('opened_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=8, max_digits=20)),
                ('price', models.DecimalField(decimal_places=8, max_digits=20)),
                ('fee', models.DecimalField(decimal_places=8, max_digits=20)),
                ('executed_at', models.DateTimeField(auto_now_add=True)),
                ('external_trade_id', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TradingPair',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('base_currency', models.CharField(max_length=10)),
                ('quote_currency', models.CharField(max_length=10)),
                ('market_type', models.CharField(choices=[('crypto', 'Cryptocurrency'), ('stock', 'Stock'), ('forex', 'Forex'), ('commodity', 'Commodity'), ('bond', 'Bond'), ('etf', 'ETF'), ('index', 'Index')], max_length=20)),
                ('exchange', models.CharField(blank=True, max_length=50)),
                ('isin', models.CharField(blank=True, max_length=12)),
                ('country_code', models.CharField(blank=True, max_length=2)),
                ('sector', models.CharField(blank=True, max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('min_order_size', models.DecimalField(decimal_places=8, max_digits=20)),
                ('max_order_size', models.DecimalField(decimal_places=8, max_digits=20)),
                ('price_precision', models.IntegerField(default=2)),
                ('quantity_precision', models.IntegerField(default=8)),
                ('trading_fee_percentage', models.DecimalField(decimal_places=4, max_digits=5)),
                ('allow_short_selling', models.BooleanField(default=False)),
                ('allow_fractional_shares', models.BooleanField(default=False)),
                ('margin_requirement', models.DecimalField(decimal_places=2, default=100, max_digits=5)),
                ('contract_size', models.DecimalField(decimal_places=2, max_digits=20, null=True)),
                ('description', models.TextField(blank=True)),
                ('logo_url', models.URLField(blank=True)),
                ('website', models.URLField(blank=True)),
                ('last_price', models.DecimalField(decimal_places=8, max_digits=20, null=True)),
                ('price_change_24h', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('volume_24h', models.DecimalField(decimal_places=2, max_digits=30, null=True)),
                ('market_cap', models.DecimalField(decimal_places=2, max_digits=30, null=True)),
                ('last_updated', models.DateTimeField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['symbol'],
            },
        ),
    ]
