# Generated by Django 5.2.8 on 2025-11-09 23:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('trading', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='position',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='trade',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trading.order'),
        ),
        migrations.AddField(
            model_name='tradingpair',
            name='asset_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trading_pairs', to='trading.assetcategory'),
        ),
        migrations.AddField(
            model_name='position',
            name='trading_pair',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trading.tradingpair'),
        ),
        migrations.AddField(
            model_name='order',
            name='trading_pair',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trading.tradingpair'),
        ),
        migrations.AddIndex(
            model_name='tradingpair',
            index=models.Index(fields=['market_type', 'is_active'], name='trading_tra_market__868f58_idx'),
        ),
        migrations.AddIndex(
            model_name='tradingpair',
            index=models.Index(fields=['symbol'], name='trading_tra_symbol_dfdd86_idx'),
        ),
    ]
