# Generated by Django 5.2.8 on 2025-11-27 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assetcategory',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
