# Generated by Django 5.2.8 on 2025-11-27 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0003_assetcategory_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='tradingpair',
            name='percentage_change_24h',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
    ]
