# Generated by Django 5.2.8 on 2025-11-27 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0004_tradingpair_percentage_change_24h'),
    ]

    operations = [
        migrations.AddField(
            model_name='tradingpair',
            name='close',
            field=models.DecimalField(decimal_places=8, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='tradingpair',
            name='high',
            field=models.DecimalField(decimal_places=8, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='tradingpair',
            name='low',
            field=models.DecimalField(decimal_places=8, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='tradingpair',
            name='open',
            field=models.DecimalField(decimal_places=8, max_digits=20, null=True),
        ),
    ]
