# Generated by Django 5.2.8 on 2025-11-27 23:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0005_tradingpair_close_tradingpair_high_tradingpair_low_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='trade',
            options={'ordering': ['-executed_at']},
        ),
        migrations.AddField(
            model_name='order',
            name='expiration_time',
            field=models.DateTimeField(blank=True, help_text='Exact time when order expires', null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='expiration_type',
            field=models.CharField(choices=[('60s', '60 Seconds'), ('2m', '2 Minutes'), ('5m', '5 Minutes'), ('10m', '10 Minutes'), ('15m', '15 Minutes'), ('30m', '30 Minutes'), ('1h', '1 Hour'), ('2h', '2 Hours'), ('4h', '4 Hours'), ('1d', '1 Day (End of Day)'), ('1w', '1 Week (End of Week)'), ('1M', '1 Month (End of Month)'), ('gtc', 'Good Till Cancelled')], default='gtc', help_text='Order expiration type', max_length=5),
        ),
        migrations.AddField(
            model_name='order',
            name='leverage',
            field=models.CharField(choices=[('1', '1x (No Leverage)'), ('2', '2x'), ('3', '3x'), ('5', '5x'), ('10', '10x'), ('20', '20x'), ('25', '25x'), ('50', '50x'), ('75', '75x'), ('100', '100x'), ('125', '125x')], default='1', help_text='Position leverage multiplier', max_length=3),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_type',
            field=models.CharField(choices=[('market', 'Market Order'), ('limit', 'Limit Order'), ('stop_loss', 'Stop Order'), ('take_profit', 'Take Profit Order')], max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('open', 'Open'), ('partially_filled', 'Partially Filled'), ('filled', 'Filled'), ('cancelled', 'Cancelled'), ('rejected', 'Rejected'), ('expired', 'Expired')], default='pending', max_length=20),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['user', 'status'], name='trading_ord_user_id_d93b91_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['trading_pair', 'status'], name='trading_ord_trading_826466_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['expiration_time'], name='trading_ord_expirat_3118e2_idx'),
        ),
    ]
