# Generated by Django 5.2.8 on 2025-11-27 23:52

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0006_alter_order_options_alter_trade_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='position',
            options={'ordering': ['-opened_at']},
        ),
        migrations.AlterField(
            model_name='position',
            name='leverage',
            field=models.DecimalField(decimal_places=2, default=Decimal('1.00'), help_text='Position leverage multiplier (1.00 = no leverage)', max_digits=5),
        ),
        migrations.AlterField(
            model_name='position',
            name='stop_loss',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='position',
            name='take_profit',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True),
        ),
        migrations.AddIndex(
            model_name='position',
            index=models.Index(fields=['user', 'trading_pair'], name='trading_pos_user_id_812ec1_idx'),
        ),
    ]
