# Generated by Django 5.2.8 on 2025-11-28 18:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0007_alter_position_options_alter_position_leverage_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='tradingpair',
            name='exchange',
            field=models.CharField(blank=True, choices=[('NASDAQ', 'NASDAQ'), ('NYSE', 'New York Stock Exchange'), ('COINBASE', 'Coinbase'), ('BINANCE', 'Binance'), ('FX', 'Forex'), ('TVC', 'TradingView Commodities')], max_length=50),
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('side', models.CharField(choices=[('long', 'Long'), ('short', 'Short')], max_length=50)),
                ('quantity', models.DecimalField(decimal_places=8, max_digits=20)),
                ('price', models.DecimalField(decimal_places=8, max_digits=20)),
                ('fee', models.DecimalField(decimal_places=8, max_digits=20)),
                ('executed_at', models.DateTimeField(auto_now_add=True)),
                ('external_trade_id', models.CharField(blank=True, max_length=100)),
                ('trades', models.ManyToManyField(related_name='transactions', to='trading.trade')),
                ('trading_pair', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trading.tradingpair')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trading_transactions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
