# Generated by Django 5.2.8 on 2025-11-28 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0008_alter_tradingpair_exchange_transaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tradingpair',
            name='exchange',
            field=models.CharField(blank=True, choices=[('NASDAQ', 'NASDAQ'), ('NYSE', 'NYSE'), ('COINBASE', 'Coinbase'), ('BINANCE', 'Binance'), ('FX', 'Forex'), ('TVC', 'TradingView Commodities')], max_length=50),
        ),
        migrations.DeleteModel(
            name='Transaction',
        ),
    ]
