# Generated by Django 5.2.8 on 2025-11-28 18:38

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0009_alter_tradingpair_exchange_delete_transaction'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('deposit', 'Deposit'), ('withdrawal', 'Withdrawal'), ('transfer_to_trading', 'Transfer to Trading'), ('transfer_from_trading', 'Transfer from Trading'), ('order_fee', 'Order Fee'), ('position_open', 'Position Opened'), ('position_close', 'Position Closed'), ('profit', 'Profit'), ('loss', 'Loss'), ('commission', 'Commission'), ('refund', 'Refund'), ('bonus', 'Bonus'), ('adjustment', 'Manual Adjustment')], db_index=True, max_length=30)),
                ('balance_type', models.CharField(choices=[('deposit', 'Deposit Balance'), ('trading', 'Trading Balance')], default='deposit', help_text='Which balance this transaction affects', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Positive for credits, negative for debits', max_digits=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], db_index=True, default='completed', max_length=20)),
                ('position_side', models.CharField(choices=[('long', 'Long'), ('short', 'Short')], default='long', help_text='Position side (long or short)', max_length=5)),
                ('balance_before', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Balance before this transaction', max_digits=20)),
                ('balance_after', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Balance after this transaction', max_digits=20)),
                ('description', models.TextField(blank=True, help_text='Human-readable description of the transaction')),
                ('reference_id', models.CharField(blank=True, db_index=True, help_text='External reference ID (e.g., payment gateway transaction ID)', max_length=100)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional transaction metadata')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('order', models.ForeignKey(blank=True, help_text='Related order if applicable', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='trading.order')),
                ('position', models.ForeignKey(blank=True, help_text='Related position if applicable', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='trading.position')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='main_transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Transaction',
                'verbose_name_plural': 'Transactions',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='trading_tra_user_id_e53073_idx'), models.Index(fields=['user', 'transaction_type'], name='trading_tra_user_id_52a1f6_idx'), models.Index(fields=['user', 'balance_type'], name='trading_tra_user_id_625633_idx'), models.Index(fields=['status', '-created_at'], name='trading_tra_status_6fc988_idx')],
            },
        ),
    ]
