# Generated by Django 5.2.8 on 2025-12-05 16:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0012_position_closed_at_position_exit_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='trading.order'),
        ),
    ]
