"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 5.2.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path
from datetime import timedelta
from decouple import config, Csv
from decimal import Decimal

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config('DEBUG', default=True, cast=bool)

ALLOWED_HOSTS = config('ALLOWED_HOSTS', default=[], cast=Csv())


# Application definition

INSTALLED_APPS = [
    'jazzmin',
    # "unfold",  # before django.contrib.admin
    # "unfold.contrib.filters",  # optional, if special filters are needed
    # "unfold.contrib.forms",  # optional, if special form elements are needed
    # "unfold.contrib.inlines",  # optional, if special inlines are needed
    # "unfold.contrib.import_export",  # optional, if django-import-export package is used
    # "unfold.contrib.guardian",  # optional, if django-guardian package is used
    # "unfold.contrib.simple_history",  # optional, if django-simple-history package is used
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # 'django.contrib.sites',  # Required by allauth
    
    
    # Third party
    'rest_framework',
    'rest_framework_simplejwt',
    'rest_framework.authtoken', 
    'corsheaders',
    'channels',
    'drf_spectacular',
    'django_prometheus',
    "graphene_django",
    
    # Local apps
    'users',
    'client',
    'funds',
    'trading',
    'bots',
    'copy_trading',
    'signals',
    'loans',
    'referrals',
    'notifications',
    'realtime',
    'investment',
]

import sentry_sdk
from sentry_sdk.integrations.django import DjangoIntegration

if not DEBUG:
    sentry_sdk.init(
        dsn=os.environ.get('SENTRY_DSN'),
        integrations=[DjangoIntegration()],
        traces_sample_rate=0.1,
        send_default_pii=False
    )

# Prometheus metrics
# INSTALLED_APPS += ['django_prometheus']
# MIDDLEWARE = ['django_prometheus.middleware.PrometheusBeforeMiddleware'] + MIDDLEWARE
# MIDDLEWARE += ['django_prometheus.middleware.PrometheusAfterMiddleware']

# SITE_ID = 1


MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django_prometheus.middleware.PrometheusBeforeMiddleware',
    # 'allauth.account.middleware.AccountMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
      'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'
ASGI_APPLICATION = 'core.asgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
        'OPTIONS': {
            'timeout': 20,  # ✅ Increase from default 5 seconds
        }
    }
}

GRAPHENE = {
    "SCHEMA": "core.schema.schema"
}


# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.postgresql',
#         'NAME': os.environ.get('DB_NAME', 'trading_platform'),
#         'USER': os.environ.get('DB_USER', 'postgres'),
#         'PASSWORD': os.environ.get('DB_PASSWORD', 'postgres'),
#         'HOST': os.environ.get('DB_HOST', 'localhost'),
#         'PORT': os.environ.get('DB_PORT', '5432'),
#     }
# }


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

# Static files (CSS, JavaScript, Images)
STATIC_URL = '/static/'
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),
]
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# Media files
MEDIA_URL = config('MEDIA_URL', default='/media/')
MEDIA_ROOT = BASE_DIR / config('MEDIA_ROOT', default='media')

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Custom User Model
AUTH_USER_MODEL = 'users.User'


# settings.py
SALT_KEY = [
    'n0ORv4dmy1vO0iYAoiU7EEF2VEOe503SQR0E2MppLes=',
    'f_50qUOpxFm1UTU0lHuJl9qGfacCcFwjTian4MfEYjI=',
]



# REST Framework
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_FILTER_BACKENDS': [
        'django_filters.rest_framework.DjangoFilterBackend',
        'rest_framework.filters.OrderingFilter',
        'rest_framework.filters.SearchFilter',
    ],
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 200,
    'MAX_PAGE_SIZE': 2000,  # Allow up to 2000 items per page
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
}

# JWT Settings
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(hours=config('JWT_ACCESS_TOKEN_LIFETIME', default=2, cast=int)),
    'REFRESH_TOKEN_LIFETIME': timedelta(hours=config('JWT_REFRESH_TOKEN_LIFETIME', default=24, cast=int)),
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,
    'UPDATE_LAST_LOGIN': True,
    'ALGORITHM': 'HS256',
    'SIGNING_KEY': SECRET_KEY,
    'AUTH_HEADER_TYPES': ('Bearer',),
    'USER_ID_FIELD': 'id',
    'USER_ID_CLAIM': 'user_id',
}

# CORS
CORS_ALLOWED_ORIGINS = config("CORS_ALLOWED_ORIGINS", cast=Csv())
CORS_ALLOW_CREDENTIALS = True

# Channels
CHANNEL_LAYERS = {
    'default': {
        'BACKEND': 'channels_redis.core.RedisChannelLayer',
        'CONFIG': {
            'hosts': [config('REDIS_URL', default='redis://localhost:6379/0')],
        },
        # "CONNECTION_POOL_KWARGS": {"max_connections": 5},
    },
}

# Celery Beat Schedule
from celery.schedules import crontab

CELERY_BEAT_SCHEDULE = {
    'update-market-prices': {
        'task': 'copy_trading.tasks.update_market_prices',
        'schedule': 60.0,   # Every minute
    },
    'execute-pending-orders': {
        'task': 'copy_trading.tasks.execute_pending_orders',
        'schedule': 10.0,  # Every 10 seconds
    },
    'run-trading-bots': {
        'task': 'copy_trading.tasks.run_trading_bots',
        'schedule': 60.0,  # Every minute
    },
    
    'replicate_trade_async': {
        'task': 'copy_trading.tasks.replicate_trade_async',
        'schedule': 10.0,  # Every 10 seconds
    },
    
    'process-copy-trades': {
        'task': 'copy_trading.tasks.process_copy_trades',
        'schedule': 30.0,  # Every 30 seconds
    },
    'calculate-loan-interest': {
        'task': 'copy_trading.tasks.calculate_loan_interest',
        'schedule': crontab(hour=0, minute=0),  # Daily at midnight
    },
    'process-referral-rewards': {
        'task': 'copy_trading.tasks.process_referral_rewards',
        'schedule': crontab(hour='*/6'),  # Every 6 hours
    },
    'check-kyc-expiry': {
        'task': 'copy_trading.tasks.check_kyc_expiry',
        'schedule': crontab(hour=2, minute=0),  # Daily at 2 AM
    },
}

# Celery Configuration
CELERY_BROKER_URL = config('CELERY_BROKER_URL', default='redis://localhost:6379/1')
CELERY_RESULT_BACKEND = config('CELERY_RESULT_BACKEND', default='redis://localhost:6379/1')
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = TIME_ZONE

# CELERY_BROKER_TRANSPORT_OPTIONS = {
#     "max_connections": 5,
# }



BINANCE_API_KEY = os.environ.get('BINANCE_API_KEY', '')
BINANCE_SECRET_KEY = os.environ.get('BINANCE_SECRET_KEY', '')
ALPHA_VANTAGE_API_KEY = os.environ.get('ALPHA_VANTAGE_API_KEY', '')
POLYGON_API_KEY = os.environ.get('POLYGON_API_KEY', '')
COMMODITIES_API_KEY = os.environ.get('COMMODITIES_API_KEY', '')

# API Documentation
SPECTACULAR_SETTINGS = {
    'TITLE': 'Instagram-like API',
    'DESCRIPTION': 'Social media platform API',
    'VERSION': '1.0.0',
}

# REST Auth Settings
REST_AUTH = {
    'USE_JWT': True,
    'JWT_AUTH_HTTPONLY': False,
    'JWT_AUTH_COOKIE': None,
    'JWT_AUTH_REFRESH_COOKIE': None,
    'SESSION_LOGIN': False,
}

# After successful social login, return JWT tokens
REST_USE_JWT = True

FRONTEND_URL = config('FRONTEND_URL', default='http://localhost:8000')  

# Email Configuration
EMAIL_BACKEND = config(
    'EMAIL_BACKEND',
    default='django.core.mail.backends.console.EmailBackend'  # For development
)

# For production, use SMTP:
# EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = config('EMAIL_HOST', default='smtp.gmail.com')
EMAIL_PORT = config('EMAIL_PORT', default=587, cast=int)
EMAIL_USE_TLS = config('EMAIL_USE_TLS', default=True, cast=bool)
EMAIL_HOST_USER = config('EMAIL_HOST_USER', default='companybackup63@gmail.com')  
EMAIL_HOST_PASSWORD = config('EMAIL_HOST_PASSWORD', default='kmrg htaw akgi dblv') 
DEFAULT_FROM_EMAIL = config('DEFAULT_FROM_EMAIL', default='companybackup63@gmail.com')

FRONTEND_URL = config('FRONTEND_URL', default='http://127.0.0.1:8000') 

# Add timeout settings
EMAIL_TIMEOUT = 10  # seconds

# SSL Configuration for macOS
EMAIL_USE_SSL = False  # We're using TLS, not SSL
EMAIL_SSL_CERTFILE = None
EMAIL_SSL_KEYFILE = None

# Optional: Set custom CA bundle path (if needed)
# import certifi
# EMAIL_SSL_CERTFILE = certifi.where()

CRON_SECRET_TOKEN = config('CRON_SECRET_TOKEN', default='default-dev-token')


LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {process:d} {thread:d} {message}',
            'style': '{',
        },
        'simple': {
            'format': '{levelname} {asctime} {module} {message}',
            'style': '{',
        },
        'detailed': {
            'format': '[{asctime}] {levelname} {name} {pathname}:{lineno} - {message}',
            'style': '{',
        },
    },
    'filters': {
        'require_debug_false': {
            '()': 'django.utils.log.RequireDebugFalse',
        },
        'require_debug_true': {
            '()': 'django.utils.log.RequireDebugTrue',
        },
    },
    'handlers': {
        'console': {
            'level': 'DEBUG',
            'filters': ['require_debug_true'],
            'class': 'logging.StreamHandler',
            'formatter': 'simple'
        },
        'file_debug': {
            'level': 'DEBUG',
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': os.path.join(BASE_DIR, 'logs/debug.log'),
            'maxBytes': 1024 * 1024 * 5,  # 5 MB
            'backupCount': 5,
            'formatter': 'detailed',
        },
        'file_error': {
            'level': 'ERROR',
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': os.path.join(BASE_DIR, 'logs/error.log'),
            'maxBytes': 1024 * 1024 * 5,  # 5 MB
            'backupCount': 5,
            'formatter': 'verbose',
        },
        'file_info': {
            'level': 'INFO',
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': os.path.join(BASE_DIR, 'logs/info.log'),
            'maxBytes': 1024 * 1024 * 5,  # 5 MB
            'backupCount': 5,
            'formatter': 'detailed',
        },
        'mail_admins': {
            'level': 'ERROR',
            'filters': ['require_debug_false'],
            'class': 'django.utils.log.AdminEmailHandler',
            'include_html': True,
        }
    },
    'loggers': {
        'django': {
            'handlers': ['console', 'file_debug', 'file_error', 'file_info'],
            'level': 'INFO',
            'propagate': True,
        },
        'django.request': {
            'handlers': ['file_error', 'mail_admins', 'console'],
            'level': 'ERROR',
            'propagate': False,
        },
        'django.db.backends': {
            'handlers': ['file_debug'],
            'level': 'DEBUG',
            'propagate': False,
        },
        'django.security': {
            'handlers': ['file_error', 'mail_admins'],
            'level': 'ERROR',
            'propagate': False,
        },
        'accounts': {
            'handlers': ['console', 'file_debug', 'file_error', 'file_info'],
            'level': 'DEBUG',
            'propagate': False,
        },
        'chat': {
            'handlers': ['console', 'file_debug', 'file_error', 'file_info'],
            'level': 'DEBUG',
            'propagate': False,
        },
        'core': {
            'handlers': ['console', 'file_debug', 'file_error', 'file_info'],
            'level': 'DEBUG',
            'propagate': False,
        },
    },
    'root': {
        'handlers': ['console', 'file_error'],
        'level': 'WARNING',
    }
}


# Create logs directory if it doesn't exist
LOG_DIR = os.path.join(BASE_DIR, 'logs')
os.makedirs(LOG_DIR, exist_ok=True)


ETHEREUM_NODE_URL = config('ETHEREUM_NODE_URL', default='https://mainnet.infura.io/v3/YOUR_INFURA_PROJECT_ID')
BSC_NODE_URL = config('BSC_NODE_URL', default='https://bsc-dataseed.binance.org/')
# MASTER_SEED = config('MASTER_SEED', default='your-very-secure-master-seed')

# Blockchain Node URLs
ETHEREUM_NODE_URL = config(
    'ETHEREUM_NODE_URL', 
    default='https://mainnet.infura.io/v3/INFURA_PROJECT_ID'
)
BSC_NODE_URL = config(
    'BSC_NODE_URL',
    default='https://bsc-dataseed.binance.org/'
)
TRON_NODE_URL = config(
    'TRON_NODE_URL',
    default='https://api.trongrid.io'
)

ALPHA_VANTAGE_API_KEY = config('ALPHA_VANTAGE_API_KEY', default='your_alpha_vantage_api_key')

# Master Seed for Wallet Generation (CRITICAL - KEEP SECURE!)
MASTER_SEED = config('MASTER_SEED', default='your_very_secure_master_seed')


# Encryption key for sensitive data
FIELD_ENCRYPTION_KEY = config('FIELD_ENCRYPTION_KEY', default='your_field_encryption_key')


COPY_TRADING_CONFIG = {
    # Balance & Position Limits
    'MAX_POSITION_SIZE_PERCENTAGE': 40,  # Max 30% per trade
    'MAX_LOCKED_BALANCE_PERCENTAGE': 80,  # Max 80% locked
    'MIN_TRADING_BALANCE': Decimal('10.00'),  # Min balance to copy
    
    # Trade Limits
    'MAX_SUBSCRIPTIONS_PER_USER': 10,
    'MAX_OPEN_POSITIONS': 20,
    'MAX_DAILY_TRADES': 50,
    
    # Execution Settings
    'ENABLE_AUTO_EXECUTION': True,
    'ENABLE_MANUAL_EXECUTION': True,
    'ORDER_EXECUTION_TIMEOUT': 30,  # seconds
    
    # Performance
    'PERFORMANCE_CACHE_TTL': 300,  # 5 minutes
}