# Generated by Django 5.2.8 on 2025-11-11 05:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funds', '0003_alter_deposit_options_deposit_created_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CryptoWalletAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(choices=[('BTC', 'Bitcoin'), ('ETH', 'Ethereum'), ('USDT', 'Tether USD'), ('USDC', 'USD Coin'), ('BNB', 'Binance Coin')], max_length=10)),
                ('network', models.CharField(choices=[('BTC', 'Bitcoin'), ('ETH', 'Ethereum (ERC-20)'), ('BSC', 'Binance Smart Chain (BEP-20)'), ('TRC20', 'Tron (TRC-20)')], max_length=10)),
                ('address', models.CharField(db_index=True, max_length=100, unique=True)),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to='qr_codes/')),
                ('derivation_path', models.CharField(blank=True, max_length=100)),
                ('address_index', models.IntegerField(default=0)),
                ('total_received', models.DecimalField(decimal_places=18, default=0, max_digits=30)),
                ('total_deposits', models.IntegerField(default=0)),
                ('last_checked', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crypto_addresses', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DepositMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(max_length=10)),
                ('network', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=100)),
                ('min_deposit', models.DecimalField(decimal_places=18, max_digits=30)),
                ('max_deposit', models.DecimalField(blank=True, decimal_places=18, max_digits=30, null=True)),
                ('deposit_fee_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('deposit_fee_fixed', models.DecimalField(decimal_places=18, default=0, max_digits=30)),
                ('required_confirmations', models.IntegerField(default=3)),
                ('block_time_seconds', models.IntegerField(default=15)),
                ('contract_address', models.CharField(blank=True, max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['order', 'currency'],
                'unique_together': {('currency', 'network')},
            },
        ),
        migrations.CreateModel(
            name='PendingDeposit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(max_length=10)),
                ('network', models.CharField(max_length=10)),
                ('amount', models.DecimalField(decimal_places=18, max_digits=30)),
                ('tx_hash', models.CharField(db_index=True, max_length=100, unique=True)),
                ('from_address', models.CharField(max_length=100)),
                ('block_number', models.BigIntegerField(blank=True, null=True)),
                ('confirmations', models.IntegerField(default=0)),
                ('required_confirmations', models.IntegerField(default=3)),
                ('status', models.CharField(choices=[('detected', 'Detected'), ('confirming', 'Confirming'), ('completed', 'Completed'), ('failed', 'Failed')], default='detected', max_length=20)),
                ('detected_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='funds.transaction')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('wallet_address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='funds.cryptowalletaddress')),
            ],
            options={
                'ordering': ['-detected_at'],
            },
        ),
        migrations.AddIndex(
            model_name='cryptowalletaddress',
            index=models.Index(fields=['address'], name='funds_crypt_address_b4b21c_idx'),
        ),
        migrations.AddIndex(
            model_name='cryptowalletaddress',
            index=models.Index(fields=['user', 'is_active'], name='funds_crypt_user_id_6015ca_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='cryptowalletaddress',
            unique_together={('user', 'currency', 'network')},
        ),
        migrations.AddIndex(
            model_name='pendingdeposit',
            index=models.Index(fields=['tx_hash'], name='funds_pendi_tx_hash_93fcad_idx'),
        ),
        migrations.AddIndex(
            model_name='pendingdeposit',
            index=models.Index(fields=['status', 'detected_at'], name='funds_pendi_status_d6660d_idx'),
        ),
    ]
