# Generated by Django 5.2.8 on 2025-11-09 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CopiedTrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CopyTradingSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('copy_percentage', models.DecimalField(decimal_places=2, default=100, max_digits=5)),
                ('max_position_size', models.DecimalField(decimal_places=8, max_digits=20, null=True)),
                ('stop_loss_percentage', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Trader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(max_length=100)),
                ('bio', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('total_followers', models.IntegerField(default=0)),
                ('total_profit', models.DecimalField(decimal_places=2, max_digits=20)),
                ('profit_percentage', models.DecimalField(decimal_places=2, max_digits=10)),
                ('win_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('total_trades', models.IntegerField(default=0)),
                ('risk_score', models.IntegerField(default=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
