# Generated by Django 5.2.8 on 2025-11-09 23:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('copy_trading', '0001_initial'),
        ('trading', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='copiedtrade',
            name='follower_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follower_order', to='trading.order'),
        ),
        migrations.AddField(
            model_name='copiedtrade',
            name='master_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='master_order', to='trading.order'),
        ),
    ]
