# Generated by Django 5.2.8 on 2025-12-01 02:53

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('copy_trading', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='copiedtrade',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Execution'), ('completed', 'Completed'), ('rejected', 'Rejected by Follower'), ('failed', 'Failed Execution')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='copytradingsubscription',
            name='execution_mode',
            field=models.CharField(choices=[('manual', 'Manual (Requires confirmation)'), ('auto', 'Auto (Instant execution)')], default='auto', max_length=20, verbose_name='Trade Execution Mode'),
        ),
        migrations.AddField(
            model_name='copytradingsubscription',
            name='fixed_amount_per_trade',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True, verbose_name='Fixed Amount per Trade'),
        ),
        migrations.AddField(
            model_name='copytradingsubscription',
            name='sizing_mode',
            field=models.CharField(choices=[('proportional', 'Proportional (Same % of capital)'), ('fixed', 'Fixed (Fixed amount per trade)')], default='proportional', max_length=20, verbose_name='Trade Sizing Mode'),
        ),
        migrations.AlterField(
            model_name='copytradingsubscription',
            name='copy_percentage',
            field=models.DecimalField(decimal_places=2, default=100, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('100.00'))]),
        ),
    ]
