# Generated by Django 5.2.8 on 2025-12-01 03:45

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('copy_trading', '0004_copiedtrade_status_and_more'),
        ('trading', '0011_position_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CopyTradingPerformance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_trades', models.IntegerField(default=0)),
                ('winning_trades', models.IntegerField(default=0)),
                ('losing_trades', models.IntegerField(default=0)),
                ('total_profit_loss', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=20)),
                ('total_invested', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total amount invested through this subscription', max_digits=20)),
                ('win_rate', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('average_profit_per_trade', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=20)),
                ('average_loss_per_trade', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=20)),
                ('best_trade_profit', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=20)),
                ('worst_trade_loss', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=20)),
                ('last_trade_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Copy Trading Performance',
                'verbose_name_plural': 'Copy Trading Performance',
                'db_table': 'copy_trading_performance',
            },
        ),
        migrations.AlterModelOptions(
            name='copiedtrade',
            options={'ordering': ['-created_at'], 'verbose_name': 'Copied Trade', 'verbose_name_plural': 'Copied Trades'},
        ),
        migrations.AlterModelOptions(
            name='copytradingsubscription',
            options={'verbose_name': 'Copy Trading Subscription', 'verbose_name_plural': 'Copy Trading Subscriptions'},
        ),
        migrations.AlterModelOptions(
            name='trader',
            options={'verbose_name': 'Trader', 'verbose_name_plural': 'Traders'},
        ),
        migrations.AddField(
            model_name='copiedtrade',
            name='allocated_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Dollar amount allocated from trading balance', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='copiedtrade',
            name='calculated_quantity',
            field=models.DecimalField(blank=True, decimal_places=8, help_text='Quantity calculated for this trade', max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='copiedtrade',
            name='error_message',
            field=models.TextField(blank=True, help_text='Error message if trade failed'),
        ),
        migrations.AddField(
            model_name='copiedtrade',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='copiedtrade',
            name='follower_order',
            field=models.ForeignKey(blank=True, help_text='Null for pending trades in manual mode', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='copied_as_follower', to='trading.order'),
        ),
        migrations.AlterField(
            model_name='copiedtrade',
            name='master_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='copied_as_master', to='trading.order'),
        ),
        migrations.AlterField(
            model_name='copiedtrade',
            name='subscription',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='copied_trades', to='copy_trading.copytradingsubscription'),
        ),
        migrations.AlterField(
            model_name='copytradingsubscription',
            name='copy_percentage',
            field=models.DecimalField(decimal_places=2, default=Decimal('100.00'), help_text='Percentage of available trading balance to allocate', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.01')), django.core.validators.MaxValueValidator(Decimal('100.00'))]),
        ),
        migrations.AlterField(
            model_name='copytradingsubscription',
            name='fixed_amount_per_trade',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Fixed dollar amount to allocate per trade', max_digits=20, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Fixed Amount per Trade'),
        ),
        migrations.AlterField(
            model_name='copytradingsubscription',
            name='follower',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='copy_subscriptions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='copytradingsubscription',
            name='max_position_size',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Maximum amount to allocate per trade', max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='copytradingsubscription',
            name='sizing_mode',
            field=models.CharField(choices=[('proportional', 'Proportional (Same % of trading balance)'), ('fixed', 'Fixed (Fixed amount per trade)')], default='proportional', max_length=20, verbose_name='Trade Sizing Mode'),
        ),
        migrations.AlterField(
            model_name='copytradingsubscription',
            name='stop_loss_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Stop loss percentage for copied trades', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01')), django.core.validators.MaxValueValidator(Decimal('100.00'))]),
        ),
        migrations.AlterField(
            model_name='copytradingsubscription',
            name='trader',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscribers', to='copy_trading.trader'),
        ),
        migrations.AlterField(
            model_name='trader',
            name='profit_percentage',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AlterField(
            model_name='trader',
            name='risk_score',
            field=models.IntegerField(default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AlterField(
            model_name='trader',
            name='total_profit',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=20),
        ),
        migrations.AlterField(
            model_name='trader',
            name='win_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5),
        ),
        migrations.AddIndex(
            model_name='copiedtrade',
            index=models.Index(fields=['subscription', 'status'], name='copy_tradin_subscri_09ffef_idx'),
        ),
        migrations.AddIndex(
            model_name='copiedtrade',
            index=models.Index(fields=['status', 'created_at'], name='copy_tradin_status_bc66b8_idx'),
        ),
        migrations.AddIndex(
            model_name='copiedtrade',
            index=models.Index(fields=['-created_at'], name='copy_tradin_created_79d88f_idx'),
        ),
        migrations.AddIndex(
            model_name='copytradingsubscription',
            index=models.Index(fields=['follower', 'is_active'], name='copy_tradin_followe_d47add_idx'),
        ),
        migrations.AddIndex(
            model_name='copytradingsubscription',
            index=models.Index(fields=['trader', 'is_active'], name='copy_tradin_trader__13e6bf_idx'),
        ),
        migrations.AddIndex(
            model_name='copytradingsubscription',
            index=models.Index(fields=['created_at'], name='copy_tradin_created_5a8d18_idx'),
        ),
        migrations.AddIndex(
            model_name='trader',
            index=models.Index(fields=['-total_followers'], name='copy_tradin_total_f_be12bf_idx'),
        ),
        migrations.AddIndex(
            model_name='trader',
            index=models.Index(fields=['-profit_percentage'], name='copy_tradin_profit__24a17b_idx'),
        ),
        migrations.AddIndex(
            model_name='trader',
            index=models.Index(fields=['is_active'], name='copy_tradin_is_acti_b28a3b_idx'),
        ),
        migrations.AlterModelTable(
            name='copiedtrade',
            table='copy_trading_copied_trade',
        ),
        migrations.AlterModelTable(
            name='copytradingsubscription',
            table='copy_trading_subscription',
        ),
        migrations.AlterModelTable(
            name='trader',
            table='copy_trading_trader',
        ),
        migrations.AddField(
            model_name='copytradingperformance',
            name='subscription',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='performance', to='copy_trading.copytradingsubscription'),
        ),
    ]
