# Generated by Django 5.2.8 on 2025-12-02 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('copy_trading', '0005_copytradingperformance_alter_copiedtrade_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trader',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/'),
        ),
    ]
