# Generated by Django 5.2.8 on 2025-12-03 10:56

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('copy_trading', '0006_trader_avatar'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trader',
            options={},
        ),
        migrations.RemoveIndex(
            model_name='trader',
            name='copy_tradin_total_f_be12bf_idx',
        ),
        migrations.RemoveIndex(
            model_name='trader',
            name='copy_tradin_profit__24a17b_idx',
        ),
        migrations.RemoveIndex(
            model_name='trader',
            name='copy_tradin_is_acti_b28a3b_idx',
        ),
        migrations.AddField(
            model_name='trader',
            name='minimum_investment',
            field=models.DecimalField(decimal_places=2, default=Decimal('100.00'), help_text='Minimum trading balance required to copy this trader', max_digits=20, validators=[django.core.validators.MinValueValidator(Decimal('10.00'))]),
        ),
        migrations.AlterModelTable(
            name='trader',
            table=None,
        ),
    ]
