# Generated by Django 5.2.8 on 2025-11-24 00:50

import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InvestmentPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('interest_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('duration', models.PositiveIntegerField()),
                ('duration_unit', models.CharField(choices=[('hours', 'Hours'), ('days', 'Days')], default='days', max_length=5)),
                ('plan_types', models.CharField(choices=[('1st Plan', '1st Plan'), ('2nd Plan', '2nd Plan'), ('3rd Plan', '3rd Plan'), ('4th Plan', '4th Plan'), ('5th Plan', '5th Plan')], default='1st Plan', max_length=50)),
                ('min_investment', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('max_investment', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('icon', models.ImageField(blank=True, help_text='Payment method icon', null=True, upload_to='payment_methods/')),
                ('is_active', models.BooleanField(default=True)),
                ('min_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Minimum amount allowed for this payment method', max_digits=20)),
                ('max_amount', models.DecimalField(decimal_places=2, default=Decimal('999999.99'), help_text='Maximum amount allowed for this payment method', max_digits=20)),
                ('processing_time', models.CharField(default='24-48 hours', help_text='Estimated processing time', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Payment Method',
                'verbose_name_plural': 'Payment Methods',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='InvestmentAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('available_balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Balance available for withdrawal or new investments', max_digits=20)),
                ('invested_balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total amount currently in active investments', max_digits=20)),
                ('pending_balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Balance pending confirmation or processing', max_digits=20)),
                ('total_invested', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total amount invested across all time', max_digits=20)),
                ('active_investments', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Current active investment amount', max_digits=20)),
                ('total_earned', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total earnings from investments', max_digits=20)),
                ('total_deposits', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total deposits made', max_digits=20)),
                ('total_withdrawals', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total withdrawals made', max_digits=20)),
                ('pending_withdrawals', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Amount in pending withdrawals', max_digits=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('suspended', 'Suspended'), ('disabled', 'Disabled'), ('penalized', 'Penalized'), ('blocked', 'Blocked'), ('under_review', 'Under Review')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('last_investment', models.DateTimeField(blank=True, null=True)),
                ('last_withdrawal', models.DateTimeField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='account', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Account',
                'verbose_name_plural': 'User Accounts',
                'db_table': 'user_account',
            },
        ),
        migrations.CreateModel(
            name='Investment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('roi', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_date', models.DateTimeField()),
                ('completed', models.BooleanField(default=False)),
                ('is_running', models.BooleanField(default=False)),
                ('is_reinvestment', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investments', to=settings.AUTH_USER_MODEL)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investments', to='investment.investmentplan')),
            ],
        ),
        migrations.CreateModel(
            name='InvestmentTransactions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transactionid', models.CharField(editable=False, max_length=12, unique=True)),
                ('transaction_type', models.CharField(choices=[('deposit', 'Deposit'), ('withdrawal', 'Withdrawal'), ('investment', 'Investment'), ('reinvestment', 'Reinvestment')], max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('wallet_used', models.CharField(blank=True, max_length=255, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('confirmed', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('rejected', 'Rejected'), ('reinvested', 'Reinvested')], default='pending', max_length=10)),
                ('description', models.TextField(blank=True, null=True)),
                ('investment_plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='investment.investmentplan')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions_confirmations', to=settings.AUTH_USER_MODEL)),
                ('payment_method', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='investment.paymentmethod')),
            ],
            options={
                'verbose_name': 'Transactions Confirmed/Rejected',
            },
        ),
        migrations.CreateModel(
            name='InvestmentTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('deposit', 'Deposit'), ('withdrawal', 'Withdrawal'), ('investment', 'Investment'), ('reinvestment', 'Reinvestment')], max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('wallet_used', models.CharField(blank=True, max_length=255, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('confirmed', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('rejected', 'Rejected'), ('reinvested', 'Reinvested')], default='pending', max_length=10)),
                ('transactionid', models.CharField(editable=False, max_length=12, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('investment_plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='investment.investmentplan')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to=settings.AUTH_USER_MODEL)),
                ('payment_method', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='investment.paymentmethod')),
            ],
        ),
        migrations.CreateModel(
            name='TransactionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('deposit', 'Deposit'), ('withdrawal', 'Withdrawal'), ('investment', 'Investment'), ('reinvestment', 'Reinvestment')], max_length=100)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('rejected', 'Rejected'), ('reinvested', 'Reinvested')], default='pending', max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('investment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='investment.investment')),
                ('investment_plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='investment.investmentplan')),
                ('payment_method', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='investment.paymentmethod')),
                ('transaction', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='investment.investmenttransaction')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('btc_wallet', models.CharField(blank=True, max_length=255, null=True)),
                ('eth_wallet', models.CharField(blank=True, max_length=255, null=True)),
                ('usdt_wallet', models.CharField(blank=True, max_length=255, null=True)),
                ('ltc_wallet', models.CharField(blank=True, max_length=255, null=True)),
                ('bnb_wallet', models.CharField(blank=True, max_length=255, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='investment_wallet', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Deposit',
            fields=[
                ('deposit_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('payment_proof', models.ImageField(upload_to='deposit/proofs/')),
                ('has_deposited', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('selected_crypto', models.CharField(choices=[('BTC', 'Bitcoin'), ('ETH', 'Ethereum'), ('USDT', 'Tether'), ('LTC', 'Litecoin'), ('BNB', 'Binance Coin')], default='BTC', max_length=10)),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to='deposit/qr_codes/')),
                ('payment_method', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='investment.paymentmethod')),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='investment.wallet')),
            ],
        ),
        migrations.CreateModel(
            name='Withdrawal',
            fields=[
                ('withdrawal_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('wallet_address', models.CharField(max_length=100)),
                ('withdraw_code', models.CharField(max_length=100)),
                ('pending_withdrawals', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('payment_method', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='investment.paymentmethod')),
            ],
        ),
        migrations.AddIndex(
            model_name='investment',
            index=models.Index(fields=['user', 'start_date', 'status'], name='investment__user_id_32b045_idx'),
        ),
    ]
