# Generated by Django 5.2.8 on 2025-11-24 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investment', '0004_remove_withdrawal_withdraw_code_withdrawalcode_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wallet',
            options={'verbose_name': 'Admin Wallet', 'verbose_name_plural': 'Admin Wallets'},
        ),
        migrations.RemoveField(
            model_name='wallet',
            name='user',
        ),
        migrations.AlterField(
            model_name='wallet',
            name='bnb_wallet',
            field=models.CharField(blank=True, help_text="Admin's Binance Coin wallet address", max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='btc_wallet',
            field=models.CharField(blank=True, help_text="Admin's Bitcoin wallet address", max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='eth_wallet',
            field=models.CharField(blank=True, help_text="Admin's Ethereum wallet address", max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='ltc_wallet',
            field=models.CharField(blank=True, help_text="Admin's Litecoin wallet address", max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='usdt_wallet',
            field=models.CharField(blank=True, help_text="Admin's USDT wallet address", max_length=255, null=True),
        ),
    ]
