# Generated by Django 5.2.8 on 2025-11-24 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investment', '0006_deposit_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='bnb_qr',
            field=models.ImageField(blank=True, null=True, upload_to='wallet_qr/'),
        ),
        migrations.AddField(
            model_name='wallet',
            name='btc_qr',
            field=models.ImageField(blank=True, null=True, upload_to='wallet_qr/'),
        ),
        migrations.AddField(
            model_name='wallet',
            name='eth_qr',
            field=models.ImageField(blank=True, null=True, upload_to='wallet_qr/'),
        ),
        migrations.AddField(
            model_name='wallet',
            name='ltc_qr',
            field=models.ImageField(blank=True, null=True, upload_to='wallet_qr/'),
        ),
        migrations.AddField(
            model_name='wallet',
            name='usdt_qr',
            field=models.ImageField(blank=True, null=True, upload_to='wallet_qr/'),
        ),
    ]
