# Generated by Django 5.2.8 on 2025-11-25 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('investment', '0007_wallet_bnb_qr_wallet_btc_qr_wallet_eth_qr_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deposit',
            name='qr_code',
        ),
    ]
