# Generated by Django 5.2.8 on 2025-11-25 14:08

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investment', '0008_remove_deposit_qr_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='investmentaccount',
            name='deposit_balance',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total deposit balance', max_digits=20),
        ),
        migrations.AddField(
            model_name='investmentaccount',
            name='pending_investments',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Amount in pending investments', max_digits=20),
        ),
    ]
