# Generated by Django 5.2.8 on 2025-11-26 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investment', '0009_investmentaccount_deposit_balance_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='investmentplan',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='investmentplan',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='investmentplan',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
