# Generated by Django 5.2.8 on 2025-11-26 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investment', '0010_alter_investmentplan_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investment',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
