# Generated by Django 5.2.8 on 2025-11-26 11:10

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('investment', '0011_alter_investment_end_date'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='InvestmentAccount',
            new_name='Account',
        ),
    ]
