# Generated by Django 5.2.8 on 2025-11-26 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('investment', '0012_rename_investmentaccount_account'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Account',
        ),
    ]
