# Generated by Django 5.2.8 on 2025-11-27 12:00

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investment', '0013_delete_account'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='investmentplan',
            options={'ordering': ['created_at']},
        ),
        migrations.RemoveField(
            model_name='investmenttransaction',
            name='id',
        ),
        migrations.AlterField(
            model_name='investmenttransaction',
            name='transactionid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
