# Generated by Django 5.2.8 on 2025-11-27 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investment', '0014_alter_investmentplan_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='investment',
            name='progress_percentage',
            field=models.IntegerField(default=0),
        ),
    ]
