# Generated by Django 5.2.8 on 2025-11-09 23:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('signals', '0001_initial'),
        ('trading', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='signalnotification',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='signalplan',
            name='trading_pairs',
            field=models.ManyToManyField(to='trading.tradingpair'),
        ),
        migrations.AddField(
            model_name='signalplan',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='signals.signalprovider'),
        ),
        migrations.AddField(
            model_name='signalsubscription',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='signals.signalplan'),
        ),
        migrations.AddField(
            model_name='signalsubscription',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tradingsignal',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='signals.signalprovider'),
        ),
        migrations.AddField(
            model_name='tradingsignal',
            name='trading_pair',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trading.tradingpair'),
        ),
        migrations.AddField(
            model_name='signalnotification',
            name='signal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='signals.tradingsignal'),
        ),
    ]
