# Generated by Django 5.2.8 on 2025-11-11 01:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_deposit', models.BooleanField(default=True)),
                ('email_withdrawal', models.BooleanField(default=True)),
                ('email_trade', models.BooleanField(default=True)),
                ('email_signal', models.BooleanField(default=True)),
                ('email_kyc', models.BooleanField(default=True)),
                ('email_security', models.BooleanField(default=True)),
                ('push_deposit', models.BooleanField(default=True)),
                ('push_withdrawal', models.BooleanField(default=True)),
                ('push_trade', models.BooleanField(default=True)),
                ('push_signal', models.BooleanField(default=True)),
                ('push_kyc', models.BooleanField(default=True)),
                ('push_security', models.BooleanField(default=True)),
                ('app_all', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('deposit', 'Deposit'), ('withdrawal', 'Withdrawal'), ('trade', 'Trade Executed'), ('order', 'Order Update'), ('kyc', 'KYC Update'), ('signal', 'Trading Signal'), ('copy_trade', 'Copy Trade Executed'), ('bot', 'Bot Activity'), ('loan', 'Loan Update'), ('referral', 'Referral Reward'), ('system', 'System Notification'), ('security', 'Security Alert')], max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('link', models.CharField(blank=True, max_length=500)),
                ('related_object_type', models.CharField(blank=True, max_length=50)),
                ('related_object_id', models.IntegerField(blank=True, null=True)),
                ('is_read', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('normal', 'Normal'), ('high', 'High'), ('urgent', 'Urgent')], default='normal', max_length=10)),
                ('send_email', models.BooleanField(default=False)),
                ('email_sent', models.BooleanField(default=False)),
                ('send_push', models.BooleanField(default=False)),
                ('push_sent', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'is_read'], name='notificatio_user_id_427e4b_idx'), models.Index(fields=['created_at'], name='notificatio_created_46ad24_idx')],
            },
        ),
    ]
